/*
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jetbrains.buildServer.artifacts.s3.transfer.model;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * Represents a build instance.
 */

//TODO introduce custom deserializer to avoid having all these intermediate classes
public class Build {
  private String id;
  private String buildTypeId;
  private String number;
  private String status;
  private StateEnum state;
  private String href;
  private String artifactsDirectory;
  private BuildType buildType;
  private Files artifacts;

  public Build id(String id) {

    this.id = id;
    return this;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getProjectId() {
    return buildType.getProjectId();
  }

  public String getBuildTypeId() {
    return buildType.getId();
  }

  public void setBuildTypeId(String buildTypeId) {
    this.buildTypeId = buildTypeId;
  }

  public String getBuildTypeName() {
    return buildType.getName();
  }

  public String getBuildId() {
    return id;
  }

  public String getDirectory() {
    return getArtifactsDirectory();
  }

  public Build number(String number) {

    this.number = number;
    return this;
  }

  @javax.annotation.Nullable
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public Build status(String status) {

    this.status = status;
    return this;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Build state(StateEnum state) {

    this.state = state;
    return this;
  }

  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public Build href(String href) {

    this.href = href;
    return this;
  }

  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Build artifactsDirectory(String artifactsDirectory) {

    this.artifactsDirectory = artifactsDirectory;
    return this;
  }

  public String getArtifactsDirectory() {
    return artifactsDirectory;
  }

  public void setArtifactsDirectory(String artifactsDirectory) {
    this.artifactsDirectory = artifactsDirectory;
  }

  public Build buildType(BuildType buildType) {

    this.buildType = buildType;
    return this;
  }

  public BuildType getBuildType() {
    return buildType;
  }

  public void setBuildType(BuildType buildType) {
    this.buildType = buildType;
  }

  public Build artifacts(Files artifacts) {

    this.artifacts = artifacts;
    return this;
  }

  public Files getArtifacts() {
    return artifacts;
  }

  public void setArtifacts(Files artifacts) {
    this.artifacts = artifacts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Build build = (Build)o;
    return Objects.equals(id, build.id) &&
           Objects.equals(buildTypeId, build.buildTypeId) &&
           Objects.equals(number, build.number) &&
           Objects.equals(status, build.status) &&
           Objects.equals(state, build.state) &&
           Objects.equals(href, build.href) &&
           Objects.equals(artifactsDirectory, build.artifactsDirectory) &&
           Objects.equals(buildType, build.buildType) &&
           Objects.equals(artifacts, build.artifacts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, buildTypeId, number, status, state, href, artifactsDirectory, buildType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Build {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    buildTypeId: ").append(toIndentedString(buildTypeId)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    artifactsDirectory: ").append(toIndentedString(artifactsDirectory)).append("\n");
    sb.append("    buildType: ").append(toIndentedString(buildType)).append("\n");
    sb.append("    artifacts: ").append(toIndentedString(artifacts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public enum StateEnum {
    QUEUED("queued"),
    FINISHED("finished"),
    RUNNING("running"),
    DELETED("deleted"),
    UNKNOWN("unknown");

    private final String value;

    StateEnum(String value) {
      this.value = value;
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

}

