/*
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jetbrains.buildServer.artifacts.s3.transfer.model;

import io.swagger.annotations.ApiModel;
import java.util.Collections;
import java.util.List;

/**
 * Represents a list of Feature entities.
 */
@ApiModel(description = "Represents a list of Feature entities.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-05T13:58:36.971014+02:00[Europe/Amsterdam]")
public class Features {
  private Integer count;
  private List<Feature> projectFeature = Collections.emptyList();

  public Features() {
  }

  public Integer getCount() {
    return count;
  }

  public List<Feature> getProjectFeature() {
    return projectFeature;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public void setProjectFeature(List<Feature> projectFeature) {
    this.projectFeature = projectFeature;
  }
}

