/*
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jetbrains.buildServer.artifacts.s3.transfer.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Represents a build feature.
 */
@ApiModel(description = "Represents a build feature.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-05T13:58:36.971014+02:00[Europe/Amsterdam]")
public class Feature {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Boolean disabled;

  public static final String SERIALIZED_NAME_INHERITED = "inherited";
  @SerializedName(SERIALIZED_NAME_INHERITED)
  private Boolean inherited;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Properties properties;


  public Feature id(String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/

  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Feature name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/

  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Feature type(String type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   **/

  @ApiModelProperty(value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Feature disabled(Boolean disabled) {

    this.disabled = disabled;
    return this;
  }

  /**
   * Get disabled
   *
   * @return disabled
   **/

  @ApiModelProperty(value = "")

  public Boolean getDisabled() {
    return disabled;
  }


  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  public Feature inherited(Boolean inherited) {

    this.inherited = inherited;
    return this;
  }

  /**
   * Get inherited
   *
   * @return inherited
   **/

  @ApiModelProperty(value = "")

  public Boolean getInherited() {
    return inherited;
  }


  public void setInherited(Boolean inherited) {
    this.inherited = inherited;
  }


  public Feature href(String href) {

    this.href = href;
    return this;
  }

  /**
   * Get href
   *
   * @return href
   **/

  @ApiModelProperty(value = "")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }


  public Feature properties(Properties properties) {

    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   *
   * @return properties
   **/

  @ApiModelProperty(value = "")

  public Properties getProperties() {
    return properties;
  }


  public void setProperties(Properties properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feature feature = (Feature)o;
    return Objects.equals(this.id, feature.id) &&
           Objects.equals(this.name, feature.name) &&
           Objects.equals(this.type, feature.type) &&
           Objects.equals(this.disabled, feature.disabled) &&
           Objects.equals(this.inherited, feature.inherited) &&
           Objects.equals(this.href, feature.href) &&
           Objects.equals(this.properties, feature.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, disabled, inherited, href, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feature {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    inherited: ").append(toIndentedString(inherited)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

