/*
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jetbrains.buildServer.artifacts.s3.transfer.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents a list of Property entities.
 */
@ApiModel(description = "Represents a list of Property entities.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-05T13:58:36.971014+02:00[Europe/Amsterdam]")
public class Properties {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_PROPERTY = "property";
  @SerializedName(SERIALIZED_NAME_PROPERTY)
  private List<Property> property = null;


  public Properties count(Integer count) {

    this.count = count;
    return this;
  }

  /**
   * Get count
   *
   * @return count
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    this.count = count;
  }


  public Properties href(String href) {

    this.href = href;
    return this;
  }

  /**
   * Get href
   *
   * @return href
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }


  public Properties property(List<Property> property) {

    this.property = property;
    return this;
  }

  public Properties addPropertyItem(Property propertyItem) {
    if (this.property == null) {
      this.property = new ArrayList<Property>();
    }
    this.property.add(propertyItem);
    return this;
  }

  /**
   * Get property
   *
   * @return property
   **/
  public List<Property> getProperty() {
    return property;
  }


  public void setProperty(List<Property> property) {
    this.property = property;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Properties properties = (Properties)o;
    return Objects.equals(this.count, properties.count) &&
           Objects.equals(this.href, properties.href) &&
           Objects.equals(this.property, properties.property);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, href, property);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Properties {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

